FROM golang:1.20-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod tidy
RUN go build -o worker ./cmd/worker

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/worker .
EXPOSE 8081
CMD ["./worker"]