FROM golang:1.20-alpine AS builder
WORKDIR /app
COPY . .
RUN go mod tidy
RUN go build -o manager ./cmd/manager

FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/manager .
EXPOSE 8080
CMD ["./manager"]